#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Video:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'videoId': 'integer',
            'cameraId': 'integer',
            'cameraLabel': 'str',
            'duration': 'integer',
            'height': 'integer',
            'width': 'integer',
            'isRecording': 'bool',
            'createdAt': 'integer',
            'fileURL': 'str',
            'playURL': 'str',
            'previewURL': 'str'

        }


        #The video identifier
        self.videoId = None # integer
        #The camera identifier
        self.cameraId = None # integer
        #The camera label
        self.cameraLabel = None # str
        #The video duration, in seconds
        self.duration = None # integer
        #The video height, in pixels
        self.height = None # integer
        #The video width, in pixels
        self.width = None # integer
        #Flag indicating if the video is currently recording
        self.isRecording = None # bool
        #The video creation date
        self.createdAt = None # integer
        #The video file URL
        self.fileURL = None # str
        #URL to get informations for HLS playing
        self.playURL = None # str
        #The video preview file URL
        self.previewURL = None # str
        
